# Generated by Django 3.0.4 on 2020-03-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20200326_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
