# Generated by Django 3.0.4 on 2020-03-26 18:42

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_tool_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='about',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, null=True)),
                ('slug', models.SlugField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, default=None, max_length=250, null=True, upload_to='uploads/')),
                ('preamble', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('inspiration_text', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('resource_text', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('tool_text', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('conclusion', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('inspirations', models.ManyToManyField(to='tools.Inspiration')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alevel', to='tools.Level')),
                ('resources', models.ManyToManyField(to='tools.Resource')),
                ('tags', models.ManyToManyField(to='tools.Tag')),
                ('tools', models.ManyToManyField(to='tools.Tool')),
            ],
        ),
    ]
