# Generated by Django 3.0.4 on 2020-03-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_auto_20200326_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='youtube',
            field=models.URLField(blank=True, default='', max_length=250, null=True),
        ),
    ]
