# Generated by Django 3.0.4 on 2020-03-26 20:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_auto_20200326_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='learning_text',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='learnings',
            field=models.ManyToManyField(to='tools.Learning'),
        ),
    ]
