# Generated by Django 3.0.4 on 2020-03-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_auto_20200326_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='learnings',
            field=models.ManyToManyField(to='tools.Learning'),
        ),
    ]
