# Generated by Django 3.0.4 on 2020-03-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_tool_learnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='inspirations',
            field=models.ManyToManyField(blank=True, to='tools.Inspiration'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='learnings',
            field=models.ManyToManyField(blank=True, to='tools.Learning'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='resources',
            field=models.ManyToManyField(blank=True, to='tools.Resource'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tools.Tag'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tools',
            field=models.ManyToManyField(blank=True, to='tools.Tool'),
        ),
    ]
