# Generated by Django 3.0.4 on 2020-03-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_auto_20200326_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
