# Generated by Django 3.0.4 on 2020-03-27 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0016_auto_20200327_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='learnings',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='tools.Learning'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tools.Tag'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='learnings',
            field=models.ManyToManyField(blank=True, to='tools.Learning'),
        ),
    ]
