# Generated by Django 3.0.4 on 2020-03-29 14:49

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0018_auto_20200327_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='about',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tools.Tag'),
        ),
        migrations.AlterField(
            model_name='learning',
            name='about',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='learning',
            name='url',
            field=models.URLField(default='', help_text="If this is a Youtube URL, the video's thumbnail will be automatically used.", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='about',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='learnings',
            field=models.ManyToManyField(blank=True, null=True, to='tools.Learning'),
        ),
    ]
