# Generated by Django 3.0.4 on 2020-03-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0019_auto_20200329_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tools.Tag'),
        ),
    ]
