# Generated by Django 3.0.4 on 2020-04-03 19:10

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0020_auto_20200329_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, default=None, max_length=250, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='level',
            name='text',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
