# Generated by Django 3.0.4 on 2020-04-03 19:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0021_auto_20200403_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='learning_text',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tools.Tag'),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tools.Tag'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tools.Tag'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tools.Tag'),
        ),
    ]
