# Generated by Django 3.0.4 on 2020-04-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0022_auto_20200403_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='learnings',
            field=models.ManyToManyField(blank=True, default=None, to='tools.Learning'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='learnings',
            field=models.ManyToManyField(blank=True, to='tools.Learning'),
        ),
    ]
