# Generated by Django 3.0.4 on 2020-04-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0024_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiration',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='learning',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
