# Generated by Django 3.0.4 on 2020-05-31 14:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0025_auto_20200405_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ('-modified_date',)},
        ),
        migrations.CreateModel(
            name='ScreenCastVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('url', models.URLField(default='', max_length=250, null=True)),
                ('about', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='tools.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='screencasts',
            field=models.ManyToManyField(blank=True, to='tools.ScreenCastVideo'),
        ),
    ]
