# Generated by Django 3.0.4 on 2020-06-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0026_auto_20200531_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='screencastvideo',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
