# Generated by Django 3.0.7 on 2020-06-09 11:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0027_screencastvideo_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default='', null=True)),
                ('name', models.CharField(max_length=100)),
                ('preamble', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('image_url', models.URLField(blank=True, default='', max_length=250, null=True)),
                ('youtube', models.URLField(blank=True, default='', max_length=250, null=True)),
                ('text', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, default=None, max_length=250, null=True, upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='screencastvideo',
            options={'ordering': ('-id',)},
        ),
    ]
